# https://docs.docker.com/registry/recipes/nginx/#setting-things-up
set ${ESC}upstream_http_docker_distribution_api_version ${ESC}docker_distribution_api_version;
if (${ESC}docker_distribution_api_version = '') {
    set ${ESC}docker_distribution_api_version 'registry/2.0';
}

# add cache headers and docker API compat
add_header 'Access-Control-Allow-Origin' '*';
add_header 'Docker-Distribution-Api-Version' ${ESC}docker_distribution_api_version always;
add_header 'X-Cache-Status' ${ESC}upstream_cache_status;

# load authentication tokens from file
set_by_lua_block ${ESC}registry_token {
  return ngx.shared.tokens:get("ecr")
}

# Default /v2
location ~ ^/v2$ {
  include $NGINX_CONFIG_DIR/server/docker/proxy.conf;
}

# Pass through enabled repositories.
location ~ ^/v2/$PROXY_NAMESPACE_PATTERN/manifests/.*  {
  include $NGINX_CONFIG_DIR/server/docker/proxy.conf;
}

# Content addressable files like blobs.
# https://docs.docker.com/registry/spec/api/#blob
location ~ ^/v2/$PROXY_NAMESPACE_PATTERN/blobs/[a-z0-9]+:[a-f0-9]+$ {
  include $NGINX_CONFIG_DIR/server/docker/proxy.conf;

  # When accessing image blobs using HTTP GET AWS ECR redirects with
  # s3 buckets uri to download the image. This needs to handled by
  # nginx rather then docker client for caching.
  proxy_intercept_errors    on;
  error_page 301 302 307 =  @handle_redirect;
}

location ~ ^/v2/.*/tags/list+$ {
  # get paginated list of tags
  content_by_lua_block {
    local location, tags, cjson = ngx.var.uri, {}, require "cjson"
    while true do
      local res = ngx.location.capture(
        "/get_tags",
        { args = { req_uri = location } }
      )

      if res.status == ngx.HTTP_NOT_FOUND and table.getn(tags) == 0 then
        ngx.status = ngx.HTTP_NOT_FOUND
        ngx.print(res.body)
        ngx.exit(0)
      end

      local data = cjson.decode(res.body)
      for _,v in ipairs(data['tags']) do
        ngx.print(v)
        table.insert(tags, v)
      end

      if res.header["Link"] ~= nil then
        location = res.header["Link"]:match("/v2[^>]+")
      else
        ngx.print(cjson.encode{name = data['name'], tags = tags })
        ngx.exit(ngx.HTTP_OK)
      end
    end
  }
}

# Helper location for getting tags from upstream repository
# used for getting paginated tags.
location /get_tags {
  internal;
  include           $NGINX_CONFIG_DIR/server/docker/headers.conf;
  set_unescape_uri  ${ESC}req_uri ${ESC}arg_req_uri;
  proxy_pass        $PROXY_ECR_ENDPOINT${ESC}req_uri;
}

# No authentication headers needed as ECR returns s3 uri with details in
# query params. Also the params should be part of cache key for nginx to
# issue HIT for same image blob.
location @handle_redirect {
  set                    ${ESC}saved_redirect_location ${ESC}upstream_http_location;
  proxy_pass             ${ESC}saved_redirect_location;
  proxy_cache            cache;
  proxy_cache_key        $PROXY_CACHE_KEY;
  proxy_cache_valid      200  1y;
  proxy_cache_use_stale  error timeout invalid_header updating http_500 http_502 http_503 http_504;
  proxy_cache_lock       on;
}
