lua_shared_dict tokens 1m;

init_worker_by_lua_block {
  -- Only use a single worker
  if ngx.worker.id() ~= 0 then
    return
  end

  -- Import the token module for AWS rotation
  local ngx_aws_token = require("ngx_aws_token")
  local ngx_aws_command = "aws ecr get-authorization-token --query 'authorizationData[*].authorizationToken' --output text"

  -- Set the backing storage for ngx_aws_token
  ngx_aws_token.set_storage(ngx.shared.tokens)

  -- Schedule the ECR token rotation into the shared storage
  ngx_aws_token.rotate("ecr", ngx_aws_command, function (token)
    return "Basic " .. string.gsub(token, "%s+$", "")
  end)
}
