# shared token across workers
lua_shared_dict tokens 1m;

# will run before forking out nginx worker processes
init_worker_by_lua_block {
  -- only run on one worker
  if ngx.worker.id() ~= 0 then
    return
  end

  -- reloading call to fetch token
  local function cache_token(premature)
    if premature then return end

    local cmd = io.popen("aws ecr get-authorization-token --query 'authorizationData[*].authorizationToken' --output text")
    local token = cmd:read("*all")
    local success, exit_reason, exit_code = cmd:close()

    if not success then
      ngx.log(ngx.WARN, "Unable to fetch new token, retrying in 30...")
      ngx.timer.at(30, cache_token)
      return
    end

    ngx.log(ngx.INFO, "Refreshed ECR token in cache")
    ngx.shared.tokens:set("ecr", "Basic " .. token)
  end

  -- on init
  cache_token()

  -- periodically afterwards to refresh
  ngx.timer.every(60 * 60 * 6, cache_token)
}
