set ${ESC}url   $PROXY_ECR_ENDPOINT;

proxy_pass      ${ESC}url;
proxy_redirect  ${ESC}url $PROXY_LISTENER_SCHEME://${ESC}host:$PROXY_PORT;

if (${ESC}url ~* "^https?://([^:/]+)") {
  set ${ESC}registry $1;
}

proxy_set_header  Host               ${ESC}registry;
proxy_set_header  Authorization      ${ESC}registry_token;
proxy_set_header  X-Real-IP          ${ESC}remote_addr;
proxy_set_header  X-Forwarded-For    ${ESC}remote_addr;
proxy_set_header  X-Forwarded-User   ${ESC}registry_token;
proxy_set_header  X-Forwarded-Proto  ${ESC}scheme;
