set $url   $PROXY_ECR_ENDPOINT;

proxy_pass      $url;
proxy_redirect  $url $PROXY_LISTENER_SCHEME://$host:$PROXY_PORT;

if ($url ~* "^https?://([^:/]+)") {
  set $registry $1;
}

proxy_set_header  Host               $registry;
proxy_set_header  Authorization      $registry_token;
proxy_set_header  X-Real-IP          $remote_addr;
proxy_set_header  X-Forwarded-For    $remote_addr;
proxy_set_header  X-Forwarded-User   $registry_token;
proxy_set_header  X-Forwarded-Proto  $scheme;
